[project]
name = "web-app-in-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.1"
dependencies = [
    "flask>=3.1.3",
    "gunicorn>=25.1.0",
]
